---
# https://git.zdt.io/misc/gitlab_templates
include:
  - project: 'misc/gitlab_templates'
    ref: master
    file: '/molecule/.base-template.yml'
  - project: 'misc/gitlab_templates'
    ref: master
    file: '/.clone-before-script-template.yml'

stages:
  - libvirt.ansible-2.7.10
  - libvirt.ansible-2.8.2

# job libvirt
libvirt.ansible-2.7:
  extends: .molecule.default
  stage: libvirt.ansible-2.7.10
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.7.10-molecule-2.20.0
  script:
    - molecule test -s libvirt

# job libvirt
libvirt.ansible-2.8.2:
  extends: .molecule.default
  stage: libvirt.ansible-2.8.2
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.8.2-molecule-2.20.2
