---
extends: default
rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length:
    max: 160
  empty-lines:
    max: 2
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
